[tool.poetry.dependencies]
python = "^3.13"
gunicorn = "^21.0"
uvicorn = "^0.29.0"
asgiref = "^3.9.1"
Django = "^5.2.4"
django-admin-sortable2 = "^2.2.8"
dotenv = "^0.9.9"
pillow = "^11.3.0"
python-dotenv = "^1.1.1"
sqlparse = "^0.5.3"
tzdata = "^2025.2"
