databases:
    - name: omnistrikedb
      plan: free
      databaseName: omnistrike
      user: omnistrike

services:
    - type: web
      plan: free
      name: omnistrike
      runtime: python
      buildCommand: "./build.sh"
      startCommand: "cd src/cards && gunicorn cards.asgi:application -k uvicorn.workers.UvicornWorker"
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: omnistrikedb
                property: connectionString
          - key: SECRET_KEY
            generateValue: true
          - key: WEB_CONCURRENCY
            value: 4
