# Generated by Django 5.2.4 on 2025-08-03 17:35

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cost", models.IntegerField()),
                ("image", models.ImageField(upload_to="")),
                ("type", models.CharField(max_length=100)),
                ("collection", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("citation", models.CharField()),
            ],
        ),
    ]
