# Generated by Django 5.2.4 on 2025-08-03 18:21

import django.db.models.deletion  # type: ignore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="card",
            name="citation",
        ),
        migrations.RemoveField(
            model_name="card",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="card",
            name="type",
        ),
        migrations.AddField(
            model_name="card",
            name="attack",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="hp",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="subtype",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="card",
            name="cost",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="card",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="card",
            name="card_type",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="cards.cardtype",
            ),
            preserve_default=False,
        ),
    ]
