# Generated by Django 5.2.4 on 2025-08-03 18:29

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_cardtype_alter_card_options_remove_card_citation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="attack",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="card",
            name="hp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
