# Generated by Django 5.2.4 on 2025-08-04 02:00

import cards.models.card
import django.db.models.deletion  # type: ignore
from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_alter_card_attack_alter_card_hp"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, unique=True)),
                ("char", models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="card",
            name="cost",
        ),
        migrations.AlterField(
            model_name="card",
            name="image",
            field=models.ImageField(
                default="no-photo.jpg", upload_to=cards.models.card.rename_card_image
            ),
        ),
        migrations.CreateModel(
            name="EnergyCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="cards.card",
                    ),
                ),
                (
                    "energy_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.energytype",
                    ),
                ),
            ],
        ),
    ]
