# Generated by Django 5.2.4 on 2025-08-04 17:49

import django.db.models.deletion  # type: ignore
from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_energytype_remove_card_cost_alter_card_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=8, unique=True)),
                ("release_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="card",
            name="card_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="cards.cardtype"
            ),
        ),
        migrations.AlterField(
            model_name="energycost",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="costs",
                to="cards.card",
            ),
        ),
        migrations.AlterField(
            model_name="energycost",
            name="energy_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="cards.energytype"
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="card_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cards",
                to="cards.cardset",
            ),
        ),
    ]
