# Generated by Django 5.2.4 on 2025-08-04 17:52

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_cardset_alter_card_card_type_alter_energycost_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardset",
            name="code",
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
