# Generated by Django 5.2.4 on 2025-08-04 18:21

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0006_alter_cardset_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="number_set",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
