# Generated by Django 5.2.4 on 2025-08-04 18:46

import cards.models.card_print
import django.db.models.deletion  # type: ignore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0007_card_number_set"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="card_set",
        ),
        migrations.RemoveField(
            model_name="card",
            name="image",
        ),
        migrations.RemoveField(
            model_name="card",
            name="number_set",
        ),
        migrations.CreateModel(
            name="CardPrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="no-photo.jpg",
                        upload_to=cards.models.card_print.rename_card_image,
                    ),
                ),
                ("number_set", models.PositiveIntegerField()),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cards.card"
                    ),
                ),
                (
                    "card_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards",
                        to="cards.cardset",
                    ),
                ),
            ],
        ),
    ]
