# Generated by Django 5.2.4 on 2025-08-04 18:57

import django.db.models.deletion  # type: ignore
from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0008_remove_card_card_set_remove_card_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
