# Generated by Django 5.2.4 on 2025-08-05 00:08

import django.db.models.deletion  # type: ignore
from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0009_printtype_cardprint_print_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardprint",
            name="print_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="cards.printtype",
            ),
            preserve_default=False,
        ),
    ]
