# Generated by Django 5.2.4 on 2025-08-05 13:00

import django.db.models.deletion  # type: ignore
from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0010_cardprint_print_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardprint",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prints",
                to="cards.card",
            ),
        ),
    ]
