# Generated by Django 5.2.4 on 2025-08-05 18:52

import django.db.models.deletion  # type: ignore
from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0011_alter_cardprint_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardprint",
            name="card_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prints",
                to="cards.cardset",
            ),
        ),
        migrations.AlterField(
            model_name="cardprint",
            name="number_set",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
