# Generated by Django 5.2.4 on 2025-08-06 13:43

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0012_alter_cardprint_card_set_alter_cardprint_number_set"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintPalette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, unique=True)),
            ],
        ),
    ]
