# Generated by Django 5.2.4 on 2025-08-06 13:44

import django.db.models.deletion  # type: ignore
from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0013_printpalette"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardprint",
            name="print_palette",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prints",
                to="cards.printpalette",
            ),
            preserve_default=False,
        ),
    ]
